### ISSUE TITLE
hi. i got error  backend/backend/config/env.json

### ISSUE THREAD

**Issue by bob1o2** [christopher-luu97/transcription_webapp#1]

**Comment by christopher-luu97** [comment]
You will want to create the /config folder along with the env.json.

The code below  writes your secret key to env.json which you will then have to move into backend/backend/config.

from django.core.management.utils import get_random_secret_key
import json

secret_key = get_random_secret_key()

secret_key_json = {
    "SECRET_KEY": secret_key
}

with open('env.json', 'w') as env_file:
    json.dump(secret_key_json, env_file, indent=2)
